# Generated by Django 5.2.5 on 2025-09-02 15:03

import django.db.models.deletion
import post.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('item_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='وزن کالا (کیلوگرم)')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت کالا (تومان)')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='نام گیرنده')),
                ('receiver_address', models.TextField(verbose_name='آدرس گیرنده')),
                ('receiver_phone', models.CharField(max_length=15, verbose_name='شماره تماس گیرنده')),
                ('status', models.CharField(default='در حال پردازش', max_length=50, verbose_name='وضعیت پست')),
                ('tracking_code', models.CharField(default=post.models.generate_tracking_code, max_length=10, unique=True, verbose_name='کد رهگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
            ],
        ),
    ]
