# Generated by Django 5.2.5 on 2025-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('در حال پردازش', 'در حال پردازش'), ('ارسال شد', 'ارسال شد'), ('تحویل داده شد', 'تحویل داده شد'), ('لغو شد', 'لغو شد')], default='در حال پردازش', max_length=50, verbose_name='وضعیت پست'),
        ),
    ]
