# Generated by Django 5.2.5 on 2025-09-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_weight',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='وزن کالا (کیلوگرم)'),
        ),
    ]
