# Generated by Django 5.2.5 on 2025-09-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_item_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ارزش قیمت کالا (تومان)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='item_weight',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='وزن کالا'),
        ),
        migrations.AlterField(
            model_name='post',
            name='receiver_phone',
            field=models.CharField(max_length=12, verbose_name='شماره تماس گیرنده'),
        ),
    ]
