# Generated by Django 5.2.5 on 2025-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_item_price_alter_post_item_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='receiver_phone',
            field=models.CharField(max_length=15, verbose_name='شماره تماس گیرنده'),
        ),
    ]
