# Generated by Django 5.2.5 on 2025-09-04 19:46

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_receiver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tracking_code',
            field=models.CharField(default=post.models.generate_tracking_code, max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
