# Generated by Django 5.2.6 on 2025-09-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_weight',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='وزن کالا (کیلوگرم)'),
        ),
    ]
