# Generated by Django 5.2.6 on 2025-09-07 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_item_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='استان')),
            ],
        ),
        migrations.CreateModel(
            name='PostStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'ثبت در سیستم'), ('in_transit', 'در حال ارسال'), ('arrived', 'رسیده به استان'), ('delivered', 'تحویل داده شد')], max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='post.post', verbose_name='مرسوله')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.province', verbose_name='استان')),
            ],
        ),
    ]
