# Generated by Django 5.2.6 on 2025-09-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_province_poststatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destination_province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.province', verbose_name='استان مقصد'),
        ),
    ]
