# Generated by Django 5.2.6 on 2025-09-07 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_destination_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='destination_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.province', verbose_name='استان مقصد'),
        ),
    ]
