# Generated by Django 5.2.6 on 2025-09-10 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_destination_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_posts', to='post.province', verbose_name='استان مبدأ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='destination_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_posts', to='post.province', verbose_name='استان مقصد'),
        ),
    ]
