# Generated by Django 5.2.6 on 2025-09-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_origin_province_alter_post_destination_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='شهر')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='post.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'unique_together': {('name', 'province')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='destination_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_posts', to='post.city', verbose_name='شهر مقصد'),
        ),
        migrations.AddField(
            model_name='post',
            name='origin_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_posts', to='post.city', verbose_name='شهر مبدأ'),
        ),
    ]
