# Generated by Django 5.2.6 on 2025-09-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_city_post_destination_city_post_origin_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poststatushistory',
            options={'verbose_name': 'تاریخچه وضعیت پست', 'verbose_name_plural': 'تاریخچه وضعیت پست\u200cها'},
        ),
        migrations.AddField(
            model_name='poststatushistory',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='poststatushistory',
            name='status',
            field=models.CharField(choices=[('registered', 'ثبت در سیستم'), ('in_transit', 'در حال ارسال'), ('arrived', 'رسیده به استان/شهر'), ('delivered', 'تحویل داده شد')], max_length=50, verbose_name='وضعیت'),
        ),
    ]
