# Generated by Django 5.2.6 on 2025-09-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_poststatushistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('registered', 'ثبت در سیستم'), ('in_transit', 'رهسپار مقصد'), ('arrived', 'رسیده به استان/شهر'), ('delivered', 'تحویل داده شد'), ('canceled', 'لغو شد')], default='registered', max_length=50, verbose_name='وضعیت پست'),
        ),
        migrations.AlterField(
            model_name='poststatushistory',
            name='status',
            field=models.CharField(choices=[('registered', 'ثبت در سیستم'), ('in_transit', 'رهسپار مقصد'), ('arrived', 'رسیده به استان/شهر'), ('delivered', 'تحویل داده شد'), ('canceled', 'لغو شد')], max_length=50, verbose_name='وضعیت'),
        ),
    ]
